"""PDF calculation report generator."""

from typing import Any


def generate_pdf_report(calculation_result: dict[str, Any], output_path: str) -> str:
    """Generate a simple HTML-based PDF report."""
    steps_html = ""
    for step in calculation_result.get("steps", []):
        steps_html += f"""
        <div class="step">
            <h3>Step {step['step_number']}: {step['title']}</h3>
            <p class="formula">{step['formula']}</p>
            <p class="substitution">{step['substitution']}</p>
            <p class="result">{step['result']}</p>
            <p class="ref">Ref: {step.get('reference', '')}</p>
        </div>
        """

    summary = calculation_result.get("summary", {})
    summary_html = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in summary.items())

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ARCHITEX-CAD Calculation Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
        h1 {{ color: #0f3460; border-bottom: 2px solid #e94560; padding-bottom: 10px; }}
        .status {{ font-size: 18px; font-weight: bold; }}
        .pass {{ color: green; }}
        .fail {{ color: red; }}
        .step {{ border: 1px solid #ddd; padding: 15px; margin: 10px 0; border-radius: 4px; }}
        .formula {{ font-family: monospace; color: #0f3460; }}
        .result {{ font-weight: bold; }}
        .ref {{ font-size: 12px; color: #666; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        td {{ padding: 8px; border: 1px solid #ddd; }}
    </style>
</head>
<body>
    <h1>ARCHITEX-CAD — Calculation Report</h1>
    <p class="status {'pass' if calculation_result.get('status') == 'pass' else 'fail'}">
        Status: {calculation_result.get('status', 'unknown').upper()}
    </p>
    <h2>Summary</h2>
    <table>{summary_html}</table>
    <h2>Calculation Steps</h2>
    {steps_html}
    <p><em>Generated by ARCHITEX-CAD Calculation Engine v1.0</em></p>
</body>
</html>"""

    try:
        import pdfkit
        pdfkit.from_string(html, output_path)
    except Exception:
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        return html_path

    return output_path
