import type { ToolDef } from '../../types/toolRegistry';

/** Additional tools — merged into TOOL_REGISTRY at load time */
export const EXTENDED_TOOLS: ToolDef[] = [
  { id: 'measureArea', actionId: 'measure.area', labelKey: 'tools.measureArea', icon: 'polygon', group: 'tools.measure', tab: 'model', row: 'primary', activeWhen: 'area' },
  { id: 'measureVolume', actionId: 'measure.volume', labelKey: 'tools.measureVolume', icon: 'slab', group: 'tools.measure', tab: 'model', row: 'primary', activeWhen: 'volume' },
  { id: 'storeyFilter', actionId: 'display.storeyCycle', labelKey: 'tools.storeyFilter', icon: 'text', text: 'Sty', group: 'tools.display', tab: 'model', row: 'primary' },
  { id: 'sunStudy', actionId: 'display.sunStudy', labelKey: 'tools.sunStudy', icon: 'solar', group: 'tools.display', tab: 'model', row: 'primary' },
  { id: 'clash', actionId: 'bim.clash', labelKey: 'tools.clash', icon: 'text', text: 'Clsh', group: 'tools.measure', tab: 'model', row: 'primary', requiresModel: true, requiresTwoSelection: true },
  { id: 'drawExtrude', actionId: 'draw.extrude', labelKey: 'tools.drawExtrude', icon: 'slab', group: 'tools.drawAdv', tab: 'draw', row: 'primary', activeWhen: 'extrude' },
  { id: 'drawMove', actionId: 'draw.move', labelKey: 'tools.drawMove', icon: 'pan', group: 'tools.drawAdv', tab: 'draw', row: 'primary', activeWhen: 'move' },
  { id: 'drawRotate', actionId: 'draw.rotate', labelKey: 'tools.drawRotate', icon: 'orbit', group: 'tools.drawAdv', tab: 'draw', row: 'primary', activeWhen: 'rotate' },
  { id: 'drawCopy', actionId: 'draw.copy', labelKey: 'tools.drawCopy', icon: 'text', text: 'Cpy', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'drawMirror', actionId: 'draw.mirror', labelKey: 'tools.drawMirror', icon: 'text', text: 'Mir', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'drawArray', actionId: 'draw.array', labelKey: 'tools.drawArray', icon: 'text', text: 'Arr', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'drawExportIfc', actionId: 'draw.exportIfc', labelKey: 'tools.drawExportIfc', icon: 'boq', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'drawPolygonArea', actionId: 'draw.polygonArea', labelKey: 'tools.polygonArea', icon: 'geo', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'drawFar', actionId: 'draw.farCheck', labelKey: 'tools.farCheck', icon: 'feasibility', group: 'tools.drawAdv', tab: 'draw', row: 'primary' },
  { id: 'geoTerrain', actionId: 'geo.terrain', labelKey: 'tools.geoTerrain', icon: 'geo', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoSoil', actionId: 'geo.soil', labelKey: 'tools.geoSoil', icon: 'text', text: 'Soil', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoClimate', actionId: 'geo.climate', labelKey: 'tools.geoClimate', icon: 'text', text: 'Clim', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoSeismic', actionId: 'geo.seismic', labelKey: 'tools.geoSeismic', icon: 'seismic', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoContours', actionId: 'geo.contours', labelKey: 'tools.geoContours', icon: 'text', text: 'Cont', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoFloodOverlay', actionId: 'geo.floodOverlay', labelKey: 'tools.geoFloodOverlay', icon: 'flood', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoPolygonArea', actionId: 'geo.polygonArea', labelKey: 'tools.polygonArea', icon: 'polygon', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoRegionCut', actionId: 'geo.regionCut', labelKey: 'tools.regionCut', icon: 'text', text: 'Cut', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoRegionUnion', actionId: 'geo.regionUnion', labelKey: 'tools.regionUnion', icon: 'text', text: 'Union', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'geoEia', actionId: 'geo.eia', labelKey: 'tools.geoEia', icon: 'text', text: 'EIA', group: 'tools.geo', tab: 'geo', row: 'primary' },
  { id: 'reFar', actionId: 're.far', labelKey: 'tools.reFar', icon: 'text', text: 'FAR', group: 'tools.realestate', tab: 'realestate', row: 'primary' },
  { id: 'reSetback', actionId: 're.setback', labelKey: 'tools.reSetback', icon: 'text', text: 'Set', group: 'tools.realestate', tab: 'realestate', row: 'primary' },
  { id: 'reUnitMix', actionId: 're.unitMix', labelKey: 'tools.reUnitMix', icon: 'text', text: 'Mix', group: 'tools.realestate', tab: 'realestate', row: 'primary' },
  { id: 'reAffordable', actionId: 're.affordable', labelKey: 'tools.reAffordable', icon: 'feasibility', group: 'tools.realestate', tab: 'realestate', row: 'primary' },
  { id: 'washRainwater', actionId: 'wash.rainwater', labelKey: 'tools.washRainwater', icon: 'water', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washSeptic', actionId: 'wash.septic', labelKey: 'tools.washSeptic', icon: 'text', text: 'Sep', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washLpcdRural', actionId: 'wash.lpcdRural', labelKey: 'tools.washLpcdRural', icon: 'text', text: 'Rur', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washLpcdUrban', actionId: 'wash.lpcdUrban', labelKey: 'tools.washLpcdUrban', icon: 'text', text: 'Urb', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washLpcdSchool', actionId: 'wash.lpcdSchool', labelKey: 'tools.washLpcdSchool', icon: 'text', text: 'Sch', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washPumpHead', actionId: 'wash.pumpHead', labelKey: 'tools.washPumpHead', icon: 'pipe', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'washBoreholeCheck', actionId: 'wash.boreholeCheck', labelKey: 'tools.washBoreholeCheck', icon: 'text', text: 'Bh+', group: 'tools.wash', tab: 'wash', row: 'primary' },
  { id: 'energyMinigrid', actionId: 'energy.minigrid', labelKey: 'tools.energyMinigrid', icon: 'text', text: 'Grid', group: 'tools.energy', tab: 'energy', row: 'primary' },
  { id: 'energyRoofSolar', actionId: 'energy.roofSolar', labelKey: 'tools.energyRoofSolar', icon: 'solar', group: 'tools.energy', tab: 'energy', row: 'primary' },
  { id: 'structPavement', actionId: 'structure.pavement', labelKey: 'tools.structPavement', icon: 'text', text: 'Pav', group: 'tools.structure', tab: 'structure', row: 'primary' },
  { id: 'structDrainage', actionId: 'structure.drainage', labelKey: 'tools.structDrainage', icon: 'water', group: 'tools.structure', tab: 'structure', row: 'primary' },
  { id: 'structWind', actionId: 'structure.wind', labelKey: 'tools.structWind', icon: 'text', text: 'Wnd', group: 'tools.structure', tab: 'structure', row: 'primary' },
  { id: 'structEarthworks', actionId: 'structure.earthworks', labelKey: 'tools.structEarthworks', icon: 'geo', group: 'tools.structure', tab: 'structure', row: 'primary' },
  { id: 'roadsPavement', actionId: 'structure.pavement', labelKey: 'tools.roadsPavement', icon: 'text', text: 'Pav', group: 'tools.roads', tab: 'roads', row: 'primary' },
  { id: 'roadsDrainage', actionId: 'structure.drainage', labelKey: 'tools.roadsDrainage', icon: 'water', group: 'tools.roads', tab: 'roads', row: 'primary' },
  { id: 'roadsEarthworks', actionId: 'structure.earthworks', labelKey: 'tools.roadsEarthworks', icon: 'geo', group: 'tools.roads', tab: 'roads', row: 'primary' },
  { id: 'bimPlanTakeoff', actionId: 'bim.planTakeoff', labelKey: 'tools.bimPlanTakeoff', icon: 'text', text: '2D', group: 'tools.bim', tab: 'bim', row: 'primary', requiresModel: true },
  { id: 'bimBoolean', actionId: 'bim.booleanDiff', labelKey: 'tools.bimBoolean', icon: 'text', text: 'Bool', group: 'tools.bim', tab: 'bim', row: 'primary', requiresModel: true, requiresTwoSelection: true },
  { id: 'bimCompare', actionId: 'bim.compareModels', labelKey: 'tools.bimCompare', icon: 'text', text: 'Diff', group: 'tools.bim', tab: 'bim', row: 'primary', requiresModel: true },
  { id: 'bimIntersection', actionId: 'bim.intersectionVolume', labelKey: 'tools.bimIntersection', icon: 'text', text: 'Vol', group: 'tools.bim', tab: 'bim', row: 'primary', requiresModel: true, requiresTwoSelection: true },
  { id: 'bimExportDwg', actionId: 'bim.exportDwg', labelKey: 'tools.bimExportDwg', icon: 'text', text: 'DWG', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimEsg', actionId: 'bim.esg', labelKey: 'tools.bimEsg', icon: 'carbon', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimTender', actionId: 'bim.tender', labelKey: 'tools.bimTender', icon: 'text', text: 'Tnd', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimEia', actionId: 'bim.eia', labelKey: 'tools.bimEia', icon: 'text', text: 'EIA', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimCarbonCredits', actionId: 'bim.carbonCredits', labelKey: 'tools.bimCarbonCredits', icon: 'carbon', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimAiVariants', actionId: 'bim.aiVariants', labelKey: 'tools.bimAiVariants', icon: 'ai', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimAiProposal', actionId: 'bim.aiProposal', labelKey: 'tools.bimAiProposal', icon: 'text', text: 'Prop', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimCalcReport', actionId: 'bim.calcReport', labelKey: 'tools.bimCalcReport', icon: 'snapshot', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'bimMarketplace', actionId: 'bim.marketplaceBoq', labelKey: 'tools.bimMarketplace', icon: 'text', text: 'Mkt', group: 'tools.bim', tab: 'bim', row: 'primary' },
  { id: 'annotAdd', actionId: 'annotate.add', labelKey: 'tools.annotAdd', icon: 'text', text: 'Mk', group: 'tools.annotate', tab: 'annotate', row: 'primary', activeWhen: 'annotate' },
  { id: 'annotBcfSave', actionId: 'annotate.bcfSave', labelKey: 'tools.annotBcfSave', icon: 'snapshot', group: 'tools.annotate', tab: 'annotate', row: 'primary' },
  { id: 'annotBcfLoad', actionId: 'annotate.bcfLoad', labelKey: 'tools.annotBcfLoad', icon: 'text', text: 'BCF', group: 'tools.annotate', tab: 'annotate', row: 'primary' },
  { id: 'annotScreenshot', actionId: 'capture.snapshot', labelKey: 'tools.snapshot', icon: 'snapshot', group: 'tools.annotate', tab: 'annotate', row: 'primary' },
  { id: 'govPortfolio', actionId: 'gov.portfolio', labelKey: 'tools.govPortfolio', icon: 'feasibility', group: 'tools.gov', tab: 'gov', row: 'primary' },
  { id: 'govSnapshot', actionId: 'gov.snapshot', labelKey: 'tools.govSnapshot', icon: 'snapshot', group: 'tools.gov', tab: 'gov', row: 'primary' },
  { id: 'govCertificate', actionId: 'gov.certificate', labelKey: 'tools.govCertificate', icon: 'text', text: 'Cert', group: 'tools.gov', tab: 'gov', row: 'primary' },
  { id: 'govCashflow', actionId: 'gov.cashflow', labelKey: 'tools.govCashflow', icon: 'budget', group: 'tools.gov', tab: 'gov', row: 'primary' },
  { id: 'fieldQuickCalc', actionId: 'field.quickCalc', labelKey: 'tools.fieldQuickCalc', icon: 'text', text: 'QCalc', group: 'tools.field', tab: 'field', row: 'primary' },
  { id: 'fieldSync', actionId: 'field.syncPush', labelKey: 'tools.fieldSync', icon: 'text', text: 'Sync', group: 'tools.field', tab: 'field', row: 'primary' },
  { id: 'intelIngest', actionId: 'intelligence.ingest', labelKey: 'tools.intelIngest', icon: 'text', text: 'Twin', group: 'tools.field', tab: 'field', row: 'primary' },
  { id: 'intelPredict', actionId: 'intelligence.predictive', labelKey: 'tools.intelPredict', icon: 'ai', group: 'tools.field', tab: 'field', row: 'primary' },
  { id: 'intelCollab', actionId: 'intelligence.collabJoin', labelKey: 'tools.intelCollab', icon: 'text', text: 'Live', group: 'tools.field', tab: 'field', row: 'primary' },
  { id: 'emSatellite', actionId: 'emerging.satellite', labelKey: 'tools.emSatellite', icon: 'geo', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emDrone', actionId: 'emerging.drone', labelKey: 'tools.emDrone', icon: 'text', text: 'UAV', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emThermal', actionId: 'emerging.thermal', labelKey: 'tools.emThermal', icon: 'text', text: 'Thrm', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emBlockchain', actionId: 'emerging.blockchain', labelKey: 'tools.emBlockchain', icon: 'text', text: '⛓', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emVoice', actionId: 'emerging.voice', labelKey: 'tools.emVoice', icon: 'text', text: '🎤', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emDisaster', actionId: 'emerging.disaster', labelKey: 'tools.emDisaster', icon: 'flood', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emCvSafety', actionId: 'emerging.cvSafety', labelKey: 'tools.emCvSafety', icon: 'text', text: 'PPE', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emAr', actionId: 'emerging.ar', labelKey: 'tools.emAr', icon: 'text', text: 'AR', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
  { id: 'emMarketplace', actionId: 'emerging.marketplace', labelKey: 'tools.emMarketplace', icon: 'boq', group: 'tools.emerging', tab: 'emerging', row: 'primary' },
];

export const EXTRA_RIBBON_TABS = [
  { id: 'annotate' as const, labelKey: 'tools.tabs.annotate' },
  { id: 'roads' as const, labelKey: 'tools.tabs.roads' },
  { id: 'gov' as const, labelKey: 'tools.tabs.gov' },
  { id: 'field' as const, labelKey: 'tools.tabs.field' },
  { id: 'emerging' as const, labelKey: 'tools.tabs.emerging' },
];
